export { default as IconArrowLeft } from './icon-arrow-left.svg?react';
export { default as IconCalculator } from './icon-calculator.svg?react';
export { default as IconCheck } from './icon-check.svg?react';
export { default as IconClose } from './icon-close.svg?react';
export { default as IconCopy } from './icon-copy.svg?react';
export { default as IconLoader } from './icon-loader.svg?react';
export { default as IconScroll } from './icon-scroll.svg?react';
export { default as IconSearch } from './icon-search.svg?react';
export { default as IconUsers } from './icon-users.svg?react';
